# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

[env]
TARGET = "./target/thumbv4t-none-eabi/release/untitled"

[tasks.default]
alias = "rom"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.debug]
command = "cargo"
args = ["build"]

[tasks.release]
command = "cargo"
args = ["build", "--release"]

[tasks.rom]
dependencies = ["release"]
command = "arm-none-eabi-objcopy"
args = ["-O", "binary", "${TARGET}", "./target/untitled.gba"]

[tasks.run]
dependencies = ["rom"]
command = "cargo"
args = ["run", "--release", "--", "${@}"]

[tasks.objdump]
dependencies = ["release"]
command = "arm-none-eabi-objdump"
args = ["-x", "${TARGET}"]

[tasks.readelf]
dependencies = ["release"]
command = "readelf"
args = ["-a", "${TARGET}"]
