# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

[env]
PROJECT_CARGO_TARGET = "thumbv4t-none-eabi"
PROJECT_CARGO_PROFILE = "release"
PROJECT_CARGO_OPTIONS = { source = "${PROJECT_CARGO_PROFILE}", mapping = { "debug" = "", "release" = "--release" } }
PROJECT_ELF_BINARY = "./target/${PROJECT_CARGO_TARGET}/${PROJECT_CARGO_PROFILE}/${CARGO_MAKE_PROJECT_NAME}"
PROJECT_GBA_BINARY = "./target/${CARGO_MAKE_PROJECT_NAME}.gba"

[tasks.default]
alias = "rom"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "cargo"
args = ["build", "@@split(PROJECT_CARGO_OPTIONS, )"]

[tasks.rom]
dependencies = ["build"]
command = "arm-none-eabi-objcopy"
args = ["-O", "binary", "${PROJECT_ELF_BINARY}", "${PROJECT_GBA_BINARY}"]

[tasks.run]
dependencies = ["rom"]
command = "cargo"
args = ["run", "@@split(PROJECT_CARGO_OPTIONS, )", "--", "${@}"]
