# SPDX-FileCopyrightText: NONE
# SPDX-License-Identifier: CC0-1.0

[env]
PROJECT_TARGET = "./target/thumbv4t-none-eabi/release/untitled"
PROJECT_CARGO_FEATURES = { source = "${CARGO_MAKE_PROFILE}", mapping = { "development" = "--release", "production" = "--release --no-default-features" } }

[tasks.default]
alias = "rom"

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.debug]
command = "cargo"
args = ["build"]

[tasks.release]
command = "cargo"
args = ["build", "@@split(PROJECT_CARGO_FEATURES, )"]

[tasks.rom]
dependencies = ["release"]
command = "arm-none-eabi-objcopy"
args = ["-O", "binary", "${PROJECT_TARGET}", "./target/untitled.gba"]

[tasks.run]
dependencies = ["rom"]
command = "cargo"
args = ["run", "--release", "--", "${@}"]

[tasks.objdump]
dependencies = ["release"]
command = "arm-none-eabi-objdump"
args = ["-x", "${PROJECT_TARGET}"]

[tasks.readelf]
dependencies = ["release"]
command = "readelf"
args = ["-a", "${PROJECT_TARGET}"]
