array_width = 80
chain_width = 100
condense_wildcard_suffixes = true
empty_item_single_line = false
error_on_line_overflow = true
error_on_unformatted = true
format_code_in_doc_comments = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = false
struct_lit_width = 30
struct_variant_width = 40
use_field_init_shorthand = true
use_small_heuristics = "Off"
wrap_comments = true
