[book]
title = "gba-dev-rs"
description = "Development documentation"
language = "en"
src = "."

[build]
build-dir = "../target/book"
create-missing = false

[output.html]
default-theme = "rust"
preferred-dark-theme = "coal"
no-section-label = true
git-repository-url = "https://github.com/crawfxrd/gba-dev-rs"

[output.html.print]
enable = false
