name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: ./scripts/deps.sh

      - name: clippy
        run: cargo clippy

      - name: fmt
        run: cargo fmt --all --check

      - name: doc
        run: cargo doc

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Install dependencies
        run: ./scripts/deps.sh

      - name: Build release binary
        run: cargo build --release
