name: CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rust-src

      - name: Install ARM tools
        run: sudo apt-get update; sudo apt-get install --no-install-recommends --assume-yes binutils-arm-none-eabi gcc-arm-none-eabi

      - name: Build ELF target
        run: cargo build --release

      - name: Convert to GBA ROM
        run: arm-none-eabi-objcopy -O binary ./target/thumbv4t-none-eabi/release/untitled ./target/untitled.gba
