name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: ./scripts/deps.sh

      - name: clippy
        run: cargo clippy

      - name: fmt
        run: cargo fmt --all -- --check

      - name: doc
        run: cargo doc --no-deps

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install dependencies
        run: ./scripts/deps.sh

      - name: Build release binary
        run: cargo build --release
