name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: ./scripts/deps.sh

      - name: clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: doc
        uses: actions-rs/cargo@v1
        with:
          command: doc

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Install dependencies
        run: ./scripts/deps.sh

      - name: Build release binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
